# Generated by Django 4.2.7 on 2023-12-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
